#!/bin/bash
sedi () {
    sed --version >/dev/null 2>&1 && sed -i -- "$@" || sed -i "" "$@"
}

TEMPLATE_DIR=$HOME/template
PROJECT_NAME=$@

if [ -z "$PROJECT_NAME" ]
then
  echo Please enter a project name
  exit 1
fi

if [ -d "$PROJECT_NAME" ]
then
  echo "$PROJECT_NAME" already exists
  exit 1
fi

mkdir "$PROJECT_NAME"
cp "$TEMPLATE_DIR/Makefile" "$PROJECT_NAME"
cp "$TEMPLATE_DIR/template.tex" "$PROJECT_NAME/main.tex"
cp "$TEMPLATE_DIR/.gitignore" "$PROJECT_NAME"
cp "$TEMPLATE_DIR/references.bib" "$PROJECT_NAME"

cd "$PROJECT_NAME"
sedi "s/Title/$PROJECT_NAME/g" "$PROJECT_NAME.tex"

git init
